### ISSUE TITLE
Logging Framework for Client/Server

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/caleydo_web_container#104]
for the server we might wanna use: 
https://docs.python.org/2/library/logging.html
because it is integrated

for the client, we could stick to `console.log` but doesn't allow to enable specific modules

**Comment by sgratzl** [comment]
on the server side a first logging mechanism is already implemented.

**Comment by thinkh** [comment]
You can use the python logger as follows:

```python
import logging
_log = logging.getLogger(__name__)
_log.info('my log message')
```

**Comment by sgratzl** [comment]
and the configuration is located in `caleydo_server/config.json - logging section`. So, it can be overwritten in your local `config.json` file

**Comment by sgratzl** [comment]
see https://github.com/phovea/phovea_core/issues/14

wontfix
