### ISSUE TITLE
parseMatrix manipulates the original matrix which is passed as a reference

### ISSUE THREAD

**Issue by flekschas** [Caleydo/caleydo_web_container#144]
Between build 90 and 93 the matrix parser has been changed in a way that it manipulates the original matrix object by cutting away the first row.

Observed:
Every time `parseMatrix` is invoked the first row of the original data object is removed.

Expected:
The matrix object passed to `parseMatrix` should never be modified. Caleydo should create a deep cloned copy and work on that instead of the referenced object.

Example: http://codepen.io/anon/pen/dGBxXV

**Comment by oshaikh13** [comment]
Hi :)

This looks like a fun "first bug." Is it okay if I take a look at it? 
Looks like we need to .slice() data in the d3-parser utilities repo, before we remove the first row.
Shift mutates the original array.

```
const cols = cols_def ? cols_def : data.**slice()**.shift().slice(1);
```

I'll try to put in a PR soon in the caleydo_d3 repo,
Omar

**Comment by sgratzl** [comment]
-> moved to https://github.com/phovea/phovea_d3/issues/4
