### ISSUE TITLE
check how to provide the server URL to the client plugins

### ISSUE THREAD

**Issue by mstreit** [Caleydo/caleydo_web_container#146]

**Comment by sgratzl** [comment]
within the library, e.g. via the `data-api` property within the script tag including the library

or

via: `Caleydo.core.api = '...'; //by default '/api'`

to be tested

**Comment by sgratzl** [comment]
phovea provides the following ways: 
 * via `data-phovea-server-url` as part of the script tag
 * via `phovea.core.init({ server_url: ...}`
