### ISSUE TITLE
Add application name and short description to demo page

### ISSUE THREAD

**Issue by mstreit** [Caleydo/caleydo_web_container#148]
See http://demo.caleydo.org.

**Comment by mstreit** [comment]
![image](https://cloud.githubusercontent.com/assets/4129755/15397190/746ee3ae-1ddf-11e6-97d9-2d583fc098c7.png)

**Comment by thinkh** [comment]
I can add the following informations from the package.json (if entered)

![appjson](https://cloud.githubusercontent.com/assets/5851088/15398146/d0968cd8-1de2-11e6-8798-ac5814eaea61.png)

There is no title; only version and description.

**Comment by mstreit** [comment]
name and description is the information we wanna have..

**Comment by thinkh** [comment]
Closed with a9814f3422fcfb031c4842f424feefae1bc7cfb6
