### ISSUE TITLE
Provide meaningful description for all applications

### ISSUE THREAD

**Issue by mstreit** [Caleydo/caleydo_web_container#149]
Needed for #148.

**Comment by mstreit** [comment]
also add URL field to json

**Comment by thinkh** [comment]
@sgratzl Is it possible to extend the [package.json](http://browsenpm.org/package.json) of each repository about the following (root) properties?

* **type**: Application or Plugin
* **category**: Container, Core, Visualization, Data, ... (by only used for plugins)
* **website**: URL to Caleydo tools page (by only used for apps)

Do you have a better idea?

We need this information to create the [repo list dynamically](https://github.com/Caleydo/website/issues/71).

**Comment by sgratzl** [comment]
website -> there should be a standard url property for package.json

for the remaining ones -> I would move them within the "caleydo" entry. Such that we only have a single caleydo specific one.

**Comment by sgratzl** [comment]
by now: application = having an index.html file

**Comment by thinkh** [comment]
> website -> there should be a standard url property for package.json
There is only the "repository.url" and "bugs.url" property. But we can't use them or already using them for the github repo url.

> for the remaining ones -> I would move them within the "caleydo" entry.
That's fine for me.

> by now: application = having an index.html file
This solution might be a bit buggy, so I prefer to add a property to the package.json.

**Comment by sgratzl** [comment]
what about: https://docs.npmjs.com/files/package.json#homepage

**Comment by thinkh** [comment]
I went through all listed Caleydo Web applications and plugins and added the properties to the package.json.

If you find a package.json that misses these properties or a typo, feel free to add it. :)
