### ISSUE TITLE
Show repositories` last commit info in about dialog

### ISSUE THREAD

**Issue by thinkh** [Caleydo/caleydo_web_container#150]
It would be helpful to get a list of all used plugins/repositories as debug information in the about dialog. 

The following steps have to be done:
[ ] Read last git commit message for each repository 
[ ] Store commit message in repository.json
[ ] Provide information in about dialog

**Comment by thinkh** [comment]
For the moment we just show the last deployment date based on the modification time of caleydo_web_container/package.json in the about dialog.

**Comment by thinkh** [comment]
Read registry.json for last_deployment (in case the package.json is not available)
https://github.com/Caleydo/caleydo_server/commit/bbd75999bb94d399a17edead622bfbb507217b08

**Comment by thinkh** [comment]
The [git-last-commit](https://github.com/seymen/git-last-commit) node module might be a possible solution to get this information.

**Comment by sgratzl** [comment]
see https://github.com/phovea/phovea_bootstrap_fontawesome/issues/7
