### ISSUE TITLE
Transfer build jobs from Jenkins to Travis

### ISSUE THREAD

**Issue by mstreit** [Caleydo/caleydo_web_container#154]
Our Jenkins server hosted at TUG is not very stable and also not under our control. The plan is to switch to Travis completely. I suggest to do this bit by bit with every job that we need to update or change.

**Comment by mstreit** [comment]
@mccalluc, you have some experience with Travis, right? If yes, it would be great if you could take over this issue.

**Comment by mstreit** [comment]
The primary goal is to switch to reliable build system that is fully under our control.
Here are some options:
1. Run Jenkins on AWS (see https://aws.bitnami.com/)
2. Switch to Travis
3. Other build systems?

**Comment by mccalluc** [comment]
Starting a [document](https://docs.google.com/document/d/13jMr23mBNlvn287xb644UnsAg6aDzcFhcJFEbl855QU/edit#heading=h.61dt0ndxz2ez) to sketch out some of the considerations.

**Comment by sgratzl** [comment]
phovea provides travis configuration files
