### ISSUE TITLE
Switch to D3 v4

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/caleydo_web_container#158]
issues: 
- compatibility
- external libraries

**Comment by thinkh** [comment]
Useful links:
* https://medium.com/state-of-analytics/migrating-to-version-4-of-d3-part1-6a5e83ce8e31#.2mlpumxxl
* https://iros.github.io/d3-v4-whats-new/#1

**Comment by sgratzl** [comment]
if, we have to change it in the corresponding modules. In cases where d3 is just used internally but not exposed it is simpler, `phovea_d3` vs `phovea_vis` for instance

**Comment by sgratzl** [comment]
moved https://github.com/phovea/phovea_d3/issues/5
