### ISSUE TITLE
Yeoman for 3rd party contributors

### ISSUE THREAD

**Issue by HendrikStrobelt** [Caleydo/caleydo_web_container#37]
for 3rd-party developers we could create a yeoman package (which could be a relatively clean branch of C.web) and create a  sub-generator "cweb:plugin" --this could be very elegant for testing locally (http://yeoman.io/learning/resources.html)

**Comment by sgratzl** [comment]
a simple starting point is now: './manage.sh init' to start a new plugin by forking https://github.com/Caleydo/sample_web

**Comment by sgratzl** [comment]
see https://github.com/phovea/generator-phovea
