### ISSUE TITLE
local deployment

### ISSUE THREAD

**Issue by HendrikStrobelt** [Caleydo/caleydo_web_container#64]
Create a grunt ruleset that creates a static functional snapshot of all client site components.

**Comment by HendrikStrobelt** [comment]
reminder

**Comment by sgratzl** [comment]
in the new container there is a task called: `package_static` which generates all the dynamic files (caleydo_web.js, index.html, and config-gen.js) and copy all the static parts together. There are some configuration options, when the final site is not hosted at the root. Check the readme
