### ISSUE TITLE
repository naming conventions

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/caleydo_web_container#81]
one option: 
 * all reusable plugins: `caleydo_`?
 * application plugins can have a standalone name, e.g. stratomex.js

plugin types: 
 * server
 * server plugins
 * data plugins
 * client plugins
 * utility scripts plugins (no real plugins but e.g. utility scripts)
 * "meta"-plugins?

**Comment by thinkh** [comment]
We used `caleydo_*` for core libraries and everything with data starts with `caleydo_data_*`. Applications can have any name for branding reasons. Beside that there are no naming convention.
