### ISSUE TITLE
Asynchronisity on python side

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/caleydo_web_container#82]
Currently, all methods on the server side are synchron. Gevent for example, has internally some adapters, such that some calls won't block. 

We should discuss, whether we wanna include some aspects how we could asynchronous methods on the server side. e.g. when we are processing a lot of data or requesting some external webservice

**Comment by sgratzl** [comment]
flask has the possibility to handle a generator function which might be useful for our usage scenario. Or the use of web sockets

**Comment by sgratzl** [comment]
long run, maybe a task scheduler: http://www.celeryproject.org/

**Comment by thinkh** [comment]
Integration of Celery will be part of [caleydo_processing_queue](https://github.com/Caleydo/caleydo_processing_queue)
