### ISSUE TITLE
think about using Docker over Vagrant

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/caleydo_web_container#93]
* both have support for all three operating systems (windows, mac, linux)
 * we are just working in a linux dev environment
 * docker configuration files are commonly used nowadays
 * vagrant could also use docker as provisioner
 * less memory overhead, since no "real" vm is created

**Comment by sgratzl** [comment]
at least we should provide a docker file with a custom image

**Comment by flekschas** [comment]
Those link summarise the difference between vagrant and docker quite nicely:
- http://stackoverflow.com/a/21314566/981933 (From the founder of Vagrant)
- http://stackoverflow.com/a/22370529/981933 (And from the Docker founder)

**Comment by sgratzl** [comment]
I think we should just use Docker for deployment but not the dev environment #117
